var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                 o                              ",
   "                                                                                ",
   "                                                                                ",
   "                                                xxx                             ",
   "                                               xx!xx                            ",
   "                                               x!!!x                            ",
   "                                               xx!xx                            ",
   "               o                        xxx     xvx                         xx  ",
   "  xx           o                                                             x  ",
   "  x                     o        xxx                                         x  ",
   "  x           xx                                                   o      o  x  ",
   "  x          x  x                                                            x  ",
   "  x  @       x  x                                o         x       =         x  ",
   "  xxxxxxxxxxxx  xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                      x!!!x                          x     x                    ",
   "                      x!!!x                          x!!!!!x                    ",
   "                      x!!!x                          x!!!!!x                    ",
   "                      xxxxx                          xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                              xxxxx                                                                           ",
   "                           xxx     xxx                                                                        ",
   "                         xxx         xxx                                                                      ",
   "                        xx             xx                                                                     ",
   "                         xx!!!!!!!!!!!xx                               o                                      ",
   "                          xx!!!!!!!!!xx                               xx                                      ",
   "                            xx!!v!!xx                                  |                                      ",
   "                                                                xx            xx                              ",
   "                                                                |             |                               ",
   "                                                                                                              ",
   "                                                                                                          o   ",
   "                                                            xx                    xx                          ",
   "                             xx    xx   x                                                                xxx  ",
   "                             x     xx   x                                                                 xx  ",
   "                             x    oxx   xxxxxxxxxxxxxx           o            o                    xx     xx  ",
   "                             x     xx                x          xx            xx                          xx  ",
   "               xx xx         x    xxx       =      o x                                        xx          xx  ",
   "              xx   xx        x     xxxxxxxxxxxxxx    x                  o                      x          xx  ",
   "             xx     xx       x o   xx                x                xxxxx                    x          xx  ",
   "     @       x   o   x!!!!!!!x     xx               =x             xxx  |  xxx                 x          xx  ",
   "    xxx      x       x!!!!!!!xx    xx o xxxxxxxxxxxxxx           xxx          xx              xx          xx  ",
   "    x x      x       xxxxxxxxx     xx    |                     xx               xxx            x          xx  ",
   "!!!!x x!!!!!!x   o                 xx          |             xxx        o         xxx          x          xx  ",
   "!!!!x x!!!!!!x                     xx       o      o       xxx                      xxx        x!!!!!!!!!!xx  ",
   "!!!!x x!!!!!!x                    xxx                |    xxx      o     =    o      xxxx     xx!!!!!!!!!!xx  ",
   "!!!!x x!!!!!!x   o                 xxxxxxxxxxxxxxxxxxxxxxxxxx         xx                       x!!!!!!!!!!xx  ",
   "!!!!x x!!!!!!x                     xxxxxxxxx!!!!!!!!!xxxxxxxx                xx                x!!!!!!!!!!xx  ",
   "!!!!x x!!!!!!x            =        xxxxxx!!!!!!!!!!!!!!!xxxxx                                  x!!!!!!!!!!xx  ",
   "!!!!x x!!!!!!x!!!xx!!!!xx!!!!xx!!!!xx!!!!!!!!!!!!!!!!!!!!!!xx!!!xx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                       xx                                                                     ",
   "                                     xx  xx                                                                   ",
   "                                    x      x                                                                  ",
   "                                  xx        xx                                                                ",
   "                                 x            x                                                               ",
   "                                xx    oooo    xx                                                              ",
   "                                  x                 x                                                         ",
   "                                  xx         xx               !!!        !!!  xxx                             ",
   "                                    x       x                !x!        !x!                                   ",
   "                                     xx   xx                  x          x                                    ",
   "                                      x    x                  x   oooo   x       xxx                          ",
   "                                      x    x                  x          x      x!!!x                         ",
   "                                      x    x                  xxxxxxxxxxxx       xxx                          ",
   "                                     xx   xx       x   x      x                                               ",
   "                                      x    xxxxxxxxx   xxxxxxxx              x x                              ",
   "                                      x    x           x                    x!!!x                             ",
   "                                      x    x           x                     xxx                              ",
   "                                     xx   xx           x                                                      ",
   "                                      x    x= = = =    x            xxx                                       ",
   "                                      x    x           x           x!!!x                                      ",
   "                                      x    x    = = = =x     o      xxx       xxx                             ",
   "                                     xx   xx           x                     x!!!x                            ",
   "                                      x    x           x     x                xxv        xxx                  ",
   "                                      x    xxx         x              x                 x!!!x                 ",
   "                                                  oo   x!!!!!!!!!!!!!!x                   vx                  ",
   "                                                       x!!!!!!!!!!!!!!x                                       ",
   "        xxxxxxxxxxxxxxxxxxxxxxx                                                                               ",
   "                                                                                     xxx                      ",
   "  xxx      |xxxx|    |xxxx|          o              xxx                             x!!!x                xxx  ",
   "  x x                                             xx                                 xxx                 x x  ",
   "  x                                 xx           xx                                                        x  ",
   "  x                                x  x          x                                                         x  ",
   "  x                               x    x         xx  o        xxx                                          x  ",
   "  x   x oo x    x oo x    x oo   x      x         xx        xx                                             x  ",
   "  x                             x        x          xxx    x               x          xxx          x       x  ",
   "  x                            x          x               xx              xxx        x!!!x        xxx      x  ",
   "  x                           x            x               x   o         xx xx        xxx        xx xx     x  ",
   "  x                           xxxxxxxxxxxxxx                xx            xxx!!!!!!!!!!!!!!!!!!!!!xxx      x  ",
   "  xx!!x    x!!!!x    x!!!!x   x            x                  xxx          x!!!!!!!!!!!!!!!!!!!!!!!x    o  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                   xx!!!!!xx                                                                  ", 
   "                                    x!!!!!x                                                                   ",
   "                 xxxx               x!!!!!x                                                                   ",
   "                 x  x               x!!!!!x      =                               x                            ",
   "             =   x  x               x  v  xxxxxxxxxxxxxx                       xx xx                          ",
   "     @ xxxxxxxxxxxx  xxx                     |         x                     xx     xx                        ", 
   "   xxxxx                                               x                                        x             ",
   "                                                       x                                      xx xx           ",
   "                                                                                            xx     xx         ",
   "                                                                                                              ",
   "                          o                                            x                                      ",
   "                         xxx                              xx         xx xx                                    ",
   "                                                                   xx     xx                                  ",
   "                                       x           x                                                          ",
   "                                        xx       xx       xx                                                  ",
   "                   xxx         xxx        xx o xx                                                             ",
   "                                             x                                                                ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                          o   ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                         xxxxxxxx",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
